/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_AYMAN_EXAMPLES_Send_File_STUB_HPP_
#define V1_AYMAN_EXAMPLES_Send_File_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/ayman/examples/SendFile.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace ayman {
namespace examples {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SendFile. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SendFileStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SendFile {
 public:
    /**
    * Sends a broadcast event for NewDataAvailable. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireNewDataAvailableEvent(const uint32_t &_DataVersion, const uint64_t &_Timestamp) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SendFile.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SendFileStubRemoteEvent
{
public:
    virtual ~SendFileStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SendFile to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SendFileStub
    : public virtual CommonAPI::Stub<SendFileStubAdapter, SendFileStubRemoteEvent>
{
public:
    typedef std::function<void (bool _accepted, uint64_t _totalBytes, uint32_t _chunkSize, uint64_t _ServerTimestamp)> RequestDownloadFileReply_t;
    typedef std::function<void (std::string _data, bool _isLastChunk, uint32_t _chunkIndex_)> RequestDataReply_t;

    virtual ~SendFileStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 3);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /// This is the method that will be called on remote calls on the method RequestDownloadFile.
    virtual void RequestDownloadFile(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _DataVersion, uint64_t _ClientTimestamp, RequestDownloadFileReply_t _reply) = 0;
    /// This is the method that will be called on remote calls on the method RequestData.
    virtual void RequestData(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _chunkIndex, uint32_t _DataVersion, RequestDataReply_t _reply) = 0;
    /// Sends a broadcast event for NewDataAvailable.
    virtual void fireNewDataAvailableEvent(const uint32_t &_DataVersion, const uint64_t &_Timestamp) {
        auto stubAdapter = CommonAPI::Stub<SendFileStubAdapter, SendFileStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireNewDataAvailableEvent(_DataVersion, _Timestamp);
    }


    using CommonAPI::Stub<SendFileStubAdapter, SendFileStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SendFileStubAdapter, SendFileStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SendFileStubAdapter, SendFileStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SendFileStubRemoteEvent RemoteEventType;
    typedef ::v1::ayman::examples::SendFile StubInterface;
};

} // namespace examples
} // namespace ayman
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_AYMAN_EXAMPLES_Send_File_STUB_HPP_
