/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_AYMAN_EXAMPLES_Send_File_PROXY_HPP_
#define V1_AYMAN_EXAMPLES_Send_File_PROXY_HPP_

#include <v1/ayman/examples/SendFileProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace ayman {
namespace examples {

template <typename ... _AttributeExtensions>
class SendFileProxy
    : virtual public SendFile,
      virtual public SendFileProxyBase,
      virtual public _AttributeExtensions... {
public:
    SendFileProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SendFileProxy();

    typedef ::v1::ayman::examples::SendFile InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls RequestDownloadFile with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void RequestDownloadFile(uint32_t _DataVersion, uint64_t _ClientTimestamp, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, uint64_t &_totalBytes, uint32_t &_chunkSize, uint64_t &_ServerTimestamp, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls RequestDownloadFile with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> RequestDownloadFileAsync(const uint32_t &_DataVersion, const uint64_t &_ClientTimestamp, RequestDownloadFileAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls RequestData with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void RequestData(uint32_t _chunkIndex, uint32_t _DataVersion, CommonAPI::CallStatus &_internalCallStatus, std::string &_data, bool &_isLastChunk, uint32_t &_chunkIndex_, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls RequestData with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> RequestDataAsync(const uint32_t &_chunkIndex, const uint32_t &_DataVersion, RequestDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Returns the wrapper class that provides access to the broadcast NewDataAvailable.
     */
    virtual NewDataAvailableEvent& getNewDataAvailableEvent() {
        return delegate_->getNewDataAvailableEvent();
    }



 private:
    std::shared_ptr< SendFileProxyBase> delegate_;
};

typedef SendFileProxy<> SendFileProxyDefault;


//
// SendFileProxy Implementation
//
template <typename ... _AttributeExtensions>
SendFileProxy<_AttributeExtensions...>::SendFileProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SendFileProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SendFileProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SendFileProxy<_AttributeExtensions...>::~SendFileProxy() {
}

template <typename ... _AttributeExtensions>
void SendFileProxy<_AttributeExtensions...>::RequestDownloadFile(uint32_t _DataVersion, uint64_t _ClientTimestamp, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, uint64_t &_totalBytes, uint32_t &_chunkSize, uint64_t &_ServerTimestamp, const CommonAPI::CallInfo *_info) {
    delegate_->RequestDownloadFile(_DataVersion, _ClientTimestamp, _internalCallStatus, _accepted, _totalBytes, _chunkSize, _ServerTimestamp, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SendFileProxy<_AttributeExtensions...>::RequestDownloadFileAsync(const uint32_t &_DataVersion, const uint64_t &_ClientTimestamp, RequestDownloadFileAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->RequestDownloadFileAsync(_DataVersion, _ClientTimestamp, _callback, _info);
}
template <typename ... _AttributeExtensions>
void SendFileProxy<_AttributeExtensions...>::RequestData(uint32_t _chunkIndex, uint32_t _DataVersion, CommonAPI::CallStatus &_internalCallStatus, std::string &_data, bool &_isLastChunk, uint32_t &_chunkIndex_, const CommonAPI::CallInfo *_info) {
    delegate_->RequestData(_chunkIndex, _DataVersion, _internalCallStatus, _data, _isLastChunk, _chunkIndex_, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SendFileProxy<_AttributeExtensions...>::RequestDataAsync(const uint32_t &_chunkIndex, const uint32_t &_DataVersion, RequestDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->RequestDataAsync(_chunkIndex, _DataVersion, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SendFileProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SendFileProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SendFileProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SendFileProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SendFileProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SendFileProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace examples
} // namespace ayman
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_AYMAN_EXAMPLES_Send_File_PROXY_HPP_
