/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_AYMAN_EXAMPLES_Send_File_STUB_DEFAULT_HPP_
#define V1_AYMAN_EXAMPLES_Send_File_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/ayman/examples/SendFileStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace ayman {
namespace examples {

/**
 * Provides a default implementation for SendFileStubRemoteEvent and
 * SendFileStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SendFileStubDefault
    : public virtual SendFileStub {
public:
    COMMONAPI_EXPORT SendFileStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SendFile::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SendFileStubRemoteEvent* initStubAdapter(const std::shared_ptr< SendFileStubAdapter> &_adapter) {
        CommonAPI::Stub<SendFileStubAdapter, SendFileStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void RequestDownloadFile(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _DataVersion, uint64_t _ClientTimestamp, RequestDownloadFileReply_t _reply) {
        (void)_client;
        (void)_DataVersion;
        (void)_ClientTimestamp;
        bool accepted = false;
        uint64_t totalBytes = 0ull;
        uint32_t chunkSize = 0ul;
        uint64_t ServerTimestamp = 0ull;
        _reply(accepted, totalBytes, chunkSize, ServerTimestamp);
    }
    COMMONAPI_EXPORT virtual void RequestData(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _chunkIndex, uint32_t _DataVersion, RequestDataReply_t _reply) {
        (void)_client;
        (void)_chunkIndex;
        (void)_DataVersion;
        std::string data = "";
        bool isLastChunk = false;
        uint32_t chunkIndex_ = 0ul;
        _reply(data, isLastChunk, chunkIndex_);
    }
    COMMONAPI_EXPORT virtual void fireNewDataAvailableEvent(const uint32_t &_DataVersion, const uint64_t &_Timestamp) {
        SendFileStub::fireNewDataAvailableEvent(_DataVersion, _Timestamp);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SendFileStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SendFileStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SendFileStubDefault *defaultStub_;
    };
protected:
    SendFileStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace examples
} // namespace ayman
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_AYMAN_EXAMPLES_Send_File_STUB_DEFAULT
