/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_AYMAN_EXAMPLES_Send_File_PROXY_BASE_HPP_
#define V1_AYMAN_EXAMPLES_Send_File_PROXY_BASE_HPP_

#include <v1/ayman/examples/SendFile.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace ayman {
namespace examples {

class SendFileProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        uint32_t, uint64_t
    > NewDataAvailableEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const bool&, const uint64_t&, const uint32_t&, const uint64_t&)> RequestDownloadFileAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&, const bool&, const uint32_t&)> RequestDataAsyncCallback;

    virtual void RequestDownloadFile(uint32_t _DataVersion, uint64_t _ClientTimestamp, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, uint64_t &_totalBytes, uint32_t &_chunkSize, uint64_t &_ServerTimestamp, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> RequestDownloadFileAsync(const uint32_t &_DataVersion, const uint64_t &_ClientTimestamp, RequestDownloadFileAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void RequestData(uint32_t _chunkIndex, uint32_t _DataVersion, CommonAPI::CallStatus &_internalCallStatus, std::string &_data, bool &_isLastChunk, uint32_t &_chunkIndex_, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> RequestDataAsync(const uint32_t &_chunkIndex, const uint32_t &_DataVersion, RequestDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual NewDataAvailableEvent& getNewDataAvailableEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace examples
} // namespace ayman
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_AYMAN_EXAMPLES_Send_File_PROXY_BASE_HPP_
