/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_AYMAN_EXAMPLES_SEND_FILE_SOMEIP_PROXY_HPP_
#define V1_AYMAN_EXAMPLES_SEND_FILE_SOMEIP_PROXY_HPP_

#include <v1/ayman/examples/SendFileProxyBase.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace ayman {
namespace examples {

class SendFileSomeIPProxy
    : virtual public SendFileProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    SendFileSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~SendFileSomeIPProxy();

    virtual NewDataAvailableEvent& getNewDataAvailableEvent();

    virtual void RequestDownloadFile(uint32_t _DataVersion, uint64_t _ClientTimestamp, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, uint64_t &_totalBytes, uint32_t &_chunkSize, uint64_t &_ServerTimestamp, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> RequestDownloadFileAsync(const uint32_t &_DataVersion, const uint64_t &_ClientTimestamp, RequestDownloadFileAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void RequestData(uint32_t _chunkIndex, uint32_t _DataVersion, CommonAPI::CallStatus &_internalCallStatus, std::string &_data, bool &_isLastChunk, uint32_t &_chunkIndex_, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> RequestDataAsync(const uint32_t &_chunkIndex, const uint32_t &_DataVersion, RequestDataAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::Event<NewDataAvailableEvent, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> >, CommonAPI::Deployable< uint64_t, CommonAPI::SomeIP::IntegerDeployment<uint64_t> >> newDataAvailable_;

};

} // namespace examples
} // namespace ayman
} // namespace v1

#endif // V1_AYMAN_EXAMPLES_Send_File_SOMEIP_PROXY_HPP_
